name: Get Default Branch Name from Checkout

on:
  workflow_dispatch:
  
      steps:
      - uses: actions/checkout@v3
        with:
            repository: aht007/haemo-support-backend
            token: ${{ secrets.REQUIREMENTS_BOT_GITHUB_TOKEN }}

      - name: Output Repo Name
        run: echo ${{github.event.repository.default_branch}}
        
      - name: Output All github context
        run: echo ${{github}}
